# Generated by Django 3.1.2 on 2020-10-07 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
            ],
        ),
    ]
